### ISSUE TITLE
Integrate column level tracking prototype

### ISSUE THREAD

**Issue by robchallen** [terminological/dtrackr#23]

**Comment by robchallen** [comment]
Experiment is here:

https://github.com/terminological/dtrackr/blob/main/R/experimental/column-tracking.R

**Comment by robchallen** [comment]
Column tracking would need to work for:

- [ ] mutates
- [ ] filters
- [ ] joins (same as filters)
- [ ] bind_rows
- [ ] summarise
- [ ] grouping (?) or influences mutates / summarise outputs at least
- [ ] graphviz visualisation needs to be written
- [ ]
